# Define the Python interpreter
PYTHON=python3

# Define the default target (all)
all:sender 

# Define the target for the Sender
sender:
	python Receiver.py

# Define the target for the Receiver